### ISSUE TITLE
Code Section weren't in Contrast

### ISSUE THREAD

**Issue by stanleyowen** [Fresh-UI/freshui#2]
Hi, I have visited the [Fresh-UI docs](https://freshui.netlify.app/) recently, and I found that there are some section that isn't really contrast like:

![Docs](https://user-images.githubusercontent.com/69080584/103849190-a7995780-50d6-11eb-95a1-3805d7531bc9.jpg)
I recommend to change the color of code from `grey` become `white` (#FFFFFF), which will improve User Experiences (UI) and improve Accessibility.

**Comment by Fresh-UI** [comment]
I am just recreating the website and you can get the source by going to
https://github.com/Fresh-UI/freshui-website
